export const START_REGISTRATION = "START_REGISTRATION";

export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS ";

export const REGISTRATION_FAILED = "REGISTRATION_FAILED";

export const START_LOGIN = "START_LOGIN";

export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
