export const START_AUTHENTICATION = "START_AUTHENTICATION";
export const AUTHENTICATION_IS_SUCCESS = " AUTHENTICATION_IS_SUCCESS";
export const AUTHENTICATION_IS_FAILURE = "AUTHENTICATION_IS_FAILURE";
export const LOGIN_DETAILS = "LOGIN_DETAILS";
